apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-deployment-reader-rb
  namespace: default
subjects:
- kind: User
  name: deploy_view
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-deployment-reader
  apiGroup: rbac.authorization.k8s.io
